id: P008011
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 12:55:16.943596
source_metadata:
  id: bdr:W1KG1660
  title: ཞི་ཁྲོ་ལྷ་ཚོགས་མཐོང་བ་ཀུན་གྲོལ།
  author: ''
  volumes:
    e074c42e171244a19e1ab77e82a79ea1:
      image_group_id: I1KG1662
      title: Volume 1 of zhi khro lha tshogs mthong ba kun grol
      volume_number: 1
      total_pages: 136
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
